
trigger:
  branches:
    include:
      - main

stages:
  - stage: Build
    displayName: "Build Stage"
    pool:
      name: Digital-Signage
    jobs:
      - job: BuildJob
        displayName: "Build Job"
        steps:
          - script: |
              echo "Hello world"
              sleep 0.5
              echo "Build success"
                        
  - stage: dev
    displayName: "Dev Stage"
    dependsOn: Build
    pool:
      name: Digital-Signage

    jobs:
      - job: DevJob
        displayName: "Dev Job"
        steps:
          - script: |
              sudo cp -R /home/muneef/myagent/_work/1/s/* /var/www/html/digita1
            displayName: "Copy to Dev directory"

  - stage: PREPROD
    displayName: "PREPROD"
    dependsOn: dev
    pool:
      name: Digital-Signage

      environment: Prepod
    jobs:
      - deployment: DeployToPreprod
        displayName: "Deploy to PREPROD"
        environment: Prepod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    sudo cp -R /home/muneef/myagent/_work/1/s/* /var/www/html/digita2
                  displayName: "Copy to PREPROD directory"

  - stage: PROD
    displayName: "PROD Release"
    dependsOn: PREPROD
    pool:
      name: Digital-Signage
      environment: prod
    jobs:
      - deployment: DeployToProd
        displayName: "Deploy to PROD"
        environment: prod
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    sudo cp -R /home/muneef/myagent/_work/1/s/* /var/www/html/digita3
                    echo "Build success"
                  displayName: "Copy to PROD directory"
